### ISSUE TITLE
Build status of master is failing

### ISSUE THREAD

**Issue by thewilly** [weso/shex-lite#46]
Locally all tests pass:
![imagen](https://user-images.githubusercontent.com/10364506/78343023-84b3a300-759a-11ea-85f9-9c68a986e574.png)
But on travis they fail...

**Comment by thewilly** [comment]
Now travis claims that the library scoverage is not available: https://travis-ci.org/github/weso/shex-lite/jobs/670493746#L391

**Comment by thewilly** [comment]
Now the travis error is `The compiler bridge sources org.scala-sbt:compiler-bridge_2.13:1.1.1:compile could not be retrieved`. From here: https://travis-ci.org/github/weso/shex-lite/jobs/670496045#L398

**Comment by thewilly** [comment]
Okey so here I found an [issue](https://github.com/sbt/sbt/issues/3684) with the same error but the solution they implemented did not work for me... 

Help @alejgh @labra please...

**Comment by alejgh** [comment]
Okay, I have been doing some tests and I cannot currently build the project even locally since you made the change to the sbt version in project/build.properties. 

I think that sbt 1.1.1 is not compatible with Scala 2.13.1?

If I restore the sbt version to the original one (1.3.7) I get one fail from the test suite:
```
[info] IdentificationWalkerTest:
[info] - Check that a base redefinition is detected by the identification walker *** FAILED ***
[info]   compiler.semantic.MemoryErrorHandler.hasErrors was true (IdentificationWalkerTest.scala:55)
[info] - Check that a base declaration is detected by the identification walker
[info] PrefixDefinitionSyntaxTest:
[info] - A prefix with a bad iri is not accepted
[info] - A good formed prefix is accepted
[info] Run completed in 549 milliseconds.
[info] Total number of tests run: 20
[info] Suites: completed 3, aborted 0
[info] Tests: succeeded 19, failed 1, canceled 0, ignored 0, pending 0
[info] *** 1 TEST FAILED ***
[error] Failed tests:
[error] 	compiler.IdentificationWalkerTest
[error] (Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 18 s, completed Apr 3, 2020, 1:21:52 PM
```

I think we had this error in travis earlier in the morning.

Regarding the problems with travis and scoverage, there is this issue available https://github.com/scoverage/sbt-scoverage/issues/295

**Comment by alejgh** [comment]
@labra has also faced this problem: https://github.com/weso/utils/issues/3

**Comment by thewilly** [comment]
Yeah sbt version change was just for testing, you can change it to usual on e(1.3.7) with no problem. Will try to fix it my self. That error in the tests is also strange as in intellij report all of them pass...

**Comment by alejgh** [comment]
Should we revert the Scala version to 2.13.0 to see if it works?

**Comment by thewilly** [comment]
If you could try it meanwhile I work on the travis configuration of the hercules-ontology repo would be awesome. Otherwise will try it myself later.

**Comment by alejgh** [comment]
> Yeah sbt version change was just for testing, you can change it to usual on e(1.3.7) with no problem. Will try to fix it my self. That error in the tests is also strange as in intellij report all of them pass...

I'm running the tests locally from the command line, maybe Intellij does something else under the hood 🤔

**Comment by alejgh** [comment]
> If you could try it meanwhile I work on the travis configuration of the hercules-ontology repo would be awesome. Otherwise will try it myself later.

Yes, I will start a pull request

**Comment by thewilly** [comment]
> 
> 
> > Yeah sbt version change was just for testing, you can change it to usual on e(1.3.7) with no problem. Will try to fix it my self. That error in the tests is also strange as in intellij report all of them pass...
> 
> I'm running the tests locally from the command line, maybe Intellij does something else under the hood 🤔

Okay at the end of the day if what fails is the test I'm not so worried. At least they are being executed.
